# Railway Configuration
# This file helps Railway understand how to deploy your Next.js app

[build]
command = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10